name: Deploy Multiple React Apps to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # -------- Deploy core-js-contents App -------- #
      - name: Install Dependencies for core-js-contents
        run: npm install
        working-directory: ./core-js-contents

      - name: Build core-js-contents
        run: npm run build
        working-directory: ./core-js-contents

      - name: Deploy core-js-contents to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./core-js-contents/dist
          destination_dir: core-js-contents

      # -------- Deploy testimonials App -------- #
      - name: Install Dependencies for pricing-section-react
        run: npm install
        working-directory: ./pricing-section-react

      - name: Build pricing-section-react
        run: npm run build
        working-directory: ./pricing-section-react

      - name: Deploy pricing-section-react to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pricing-section-react/dist
          destination_dir: pricing-section-react
